### ISSUE TITLE
No byte mirroring while byte write access

### ISSUE THREAD

**Issue by sonycman** [TobiFlex/TG68K.C#5]
When CPU writes custom chipset registers in byte mode (8 bit), 16 bit data bus must be mirrored with two copies of 8 bit data.

Currently writing byte at even address leaves least significant bits in "don`t care" state, which sets custom register to unknown value.

Not compatible with 68000 mode (and possibly with 68020 either) behavior.

Thank you.

**Comment by TobiFlex** [comment]
resolved
